#!/bin/bash
source /root/.nvm/nvm.sh #this loads nvm's environment vars

git --work-tree=/var/www/gitbegin --git-dir=/var/repo/gitbegin.git checkout -f
cd /var/www/gitbegin

echo "--> Running npm install..."
npm install

echo "--> Running npm build..."
npm run prodbuild

echo "--> Restarting web server..."
npm run restartForever
