module.exports = {
  "total_count": 10632060,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/checkstyle/checkstyle/issues/2939",
      "repository_url": "https://api.github.com/repos/checkstyle/checkstyle",
      "labels_url": "https://api.github.com/repos/checkstyle/checkstyle/issues/2939/labels{/name}",
      "comments_url": "https://api.github.com/repos/checkstyle/checkstyle/issues/2939/comments",
      "events_url": "https://api.github.com/repos/checkstyle/checkstyle/issues/2939/events",
      "html_url": "https://github.com/checkstyle/checkstyle/issues/2939",
      "id": 134739737,
      "number": 2939,
      "title": "Annotate all Checks fields that are user defined options",
      "user": {
        "login": "romani",
        "id": 812984,
        "avatar_url": "https://avatars.githubusercontent.com/u/812984?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/romani",
        "html_url": "https://github.com/romani",
        "followers_url": "https://api.github.com/users/romani/followers",
        "following_url": "https://api.github.com/users/romani/following{/other_user}",
        "gists_url": "https://api.github.com/users/romani/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/romani/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/romani/subscriptions",
        "organizations_url": "https://api.github.com/users/romani/orgs",
        "repos_url": "https://api.github.com/users/romani/repos",
        "events_url": "https://api.github.com/users/romani/events{/privacy}",
        "received_events_url": "https://api.github.com/users/romani/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/checkstyle/checkstyle/labels/approved",
          "name": "approved",
          "color": "009800"
        },
        {
          "url": "https://api.github.com/repos/checkstyle/checkstyle/labels/miscellaneous",
          "name": "miscellaneous",
          "color": "5319e7"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:18Z",
      "updated_at": "2016-02-19T00:38:18Z",
      "closed_at": null,
      "body": "We have nuance in Checkstyle:\r\n`\r\nAll Class fields that are not options should be reseted to initial state as the same instance of check is reused for all files.\r\n`\r\n\r\nwe need to create special annotation in for checkstyle code to mark all Check fields that are user faced options by it. Create a UT in test part of code to validate all our Checks classes to clean heir fields in `beginTree()` method.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/nwops/puppet-repl/issues/5",
      "repository_url": "https://api.github.com/repos/nwops/puppet-repl",
      "labels_url": "https://api.github.com/repos/nwops/puppet-repl/issues/5/labels{/name}",
      "comments_url": "https://api.github.com/repos/nwops/puppet-repl/issues/5/comments",
      "events_url": "https://api.github.com/repos/nwops/puppet-repl/issues/5/events",
      "html_url": "https://github.com/nwops/puppet-repl/issues/5",
      "id": 134739733,
      "number": 5,
      "title": "list all variables currently in scope",
      "user": {
        "login": "logicminds",
        "id": 563900,
        "avatar_url": "https://avatars.githubusercontent.com/u/563900?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/logicminds",
        "html_url": "https://github.com/logicminds",
        "followers_url": "https://api.github.com/users/logicminds/followers",
        "following_url": "https://api.github.com/users/logicminds/following{/other_user}",
        "gists_url": "https://api.github.com/users/logicminds/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/logicminds/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/logicminds/subscriptions",
        "organizations_url": "https://api.github.com/users/logicminds/orgs",
        "repos_url": "https://api.github.com/users/logicminds/repos",
        "events_url": "https://api.github.com/users/logicminds/events{/privacy}",
        "received_events_url": "https://api.github.com/users/logicminds/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:15Z",
      "updated_at": "2016-02-19T00:38:15Z",
      "closed_at": null,
      "body": "",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/docker/compose/issues/2960",
      "repository_url": "https://api.github.com/repos/docker/compose",
      "labels_url": "https://api.github.com/repos/docker/compose/issues/2960/labels{/name}",
      "comments_url": "https://api.github.com/repos/docker/compose/issues/2960/comments",
      "events_url": "https://api.github.com/repos/docker/compose/issues/2960/events",
      "html_url": "https://github.com/docker/compose/issues/2960",
      "id": 134739732,
      "number": 2960,
      "title": "volume_driver in service config is unnecessary in v2 format",
      "user": {
        "login": "dnephin",
        "id": 442180,
        "avatar_url": "https://avatars.githubusercontent.com/u/442180?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dnephin",
        "html_url": "https://github.com/dnephin",
        "followers_url": "https://api.github.com/users/dnephin/followers",
        "following_url": "https://api.github.com/users/dnephin/following{/other_user}",
        "gists_url": "https://api.github.com/users/dnephin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dnephin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dnephin/subscriptions",
        "organizations_url": "https://api.github.com/users/dnephin/orgs",
        "repos_url": "https://api.github.com/users/dnephin/repos",
        "events_url": "https://api.github.com/users/dnephin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dnephin/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/docker/compose/labels/area/config",
          "name": "area/config",
          "color": "c7def8"
        },
        {
          "url": "https://api.github.com/repos/docker/compose/labels/kind/bug",
          "name": "kind/bug",
          "color": "fc2929"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": {
        "url": "https://api.github.com/repos/docker/compose/milestones/16",
        "html_url": "https://github.com/docker/compose/milestones/1.6.1",
        "labels_url": "https://api.github.com/repos/docker/compose/milestones/16/labels",
        "id": 1561731,
        "number": 16,
        "title": "1.6.1",
        "description": "",
        "creator": {
          "login": "dnephin",
          "id": 442180,
          "avatar_url": "https://avatars.githubusercontent.com/u/442180?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/dnephin",
          "html_url": "https://github.com/dnephin",
          "followers_url": "https://api.github.com/users/dnephin/followers",
          "following_url": "https://api.github.com/users/dnephin/following{/other_user}",
          "gists_url": "https://api.github.com/users/dnephin/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/dnephin/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/dnephin/subscriptions",
          "organizations_url": "https://api.github.com/users/dnephin/orgs",
          "repos_url": "https://api.github.com/users/dnephin/repos",
          "events_url": "https://api.github.com/users/dnephin/events{/privacy}",
          "received_events_url": "https://api.github.com/users/dnephin/received_events",
          "type": "User",
          "site_admin": false
        },
        "open_issues": 7,
        "closed_issues": 39,
        "state": "open",
        "created_at": "2016-02-03T19:08:50Z",
        "updated_at": "2016-02-19T00:38:15Z",
        "due_on": null,
        "closed_at": null
      },
      "comments": 0,
      "created_at": "2016-02-19T00:38:15Z",
      "updated_at": "2016-02-19T00:38:15Z",
      "closed_at": null,
      "body": "I believe `volume_driver` is only relevant for named volumed, so the driver would need to be specified in the `volumes` section, not the config section.\r\n\r\nI think we can remove `volume_driver` from the service config for v2.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/cubing/worldcubeassociation.org/issues/390",
      "repository_url": "https://api.github.com/repos/cubing/worldcubeassociation.org",
      "labels_url": "https://api.github.com/repos/cubing/worldcubeassociation.org/issues/390/labels{/name}",
      "comments_url": "https://api.github.com/repos/cubing/worldcubeassociation.org/issues/390/comments",
      "events_url": "https://api.github.com/repos/cubing/worldcubeassociation.org/issues/390/events",
      "html_url": "https://github.com/cubing/worldcubeassociation.org/pull/390",
      "id": 134739730,
      "number": 390,
      "title": "Move teams to separate tables",
      "user": {
        "login": "pedrosino",
        "id": 1881933,
        "avatar_url": "https://avatars.githubusercontent.com/u/1881933?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pedrosino",
        "html_url": "https://github.com/pedrosino",
        "followers_url": "https://api.github.com/users/pedrosino/followers",
        "following_url": "https://api.github.com/users/pedrosino/following{/other_user}",
        "gists_url": "https://api.github.com/users/pedrosino/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pedrosino/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pedrosino/subscriptions",
        "organizations_url": "https://api.github.com/users/pedrosino/orgs",
        "repos_url": "https://api.github.com/users/pedrosino/repos",
        "events_url": "https://api.github.com/users/pedrosino/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pedrosino/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:14Z",
      "updated_at": "2016-02-19T00:38:14Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/cubing/worldcubeassociation.org/pulls/390",
        "html_url": "https://github.com/cubing/worldcubeassociation.org/pull/390",
        "diff_url": "https://github.com/cubing/worldcubeassociation.org/pull/390.diff",
        "patch_url": "https://github.com/cubing/worldcubeassociation.org/pull/390.patch"
      },
      "body": "Fixes #185 \r\n\r\nThis is not done yet. Please alert me if I'm going into some wrong direction.\r\n\r\nWe have to consider also moving delegates to a \"team\" table. This could be tricky, because we have 4 types of them...",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/jfarmer91/test-bs-two/issues/11",
      "repository_url": "https://api.github.com/repos/jfarmer91/test-bs-two",
      "labels_url": "https://api.github.com/repos/jfarmer91/test-bs-two/issues/11/labels{/name}",
      "comments_url": "https://api.github.com/repos/jfarmer91/test-bs-two/issues/11/comments",
      "events_url": "https://api.github.com/repos/jfarmer91/test-bs-two/issues/11/events",
      "html_url": "https://github.com/jfarmer91/test-bs-two/pull/11",
      "id": 134739721,
      "number": 11,
      "title": "Intermediate",
      "user": {
        "login": "jfarmer91",
        "id": 15361539,
        "avatar_url": "https://avatars.githubusercontent.com/u/15361539?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jfarmer91",
        "html_url": "https://github.com/jfarmer91",
        "followers_url": "https://api.github.com/users/jfarmer91/followers",
        "following_url": "https://api.github.com/users/jfarmer91/following{/other_user}",
        "gists_url": "https://api.github.com/users/jfarmer91/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jfarmer91/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jfarmer91/subscriptions",
        "organizations_url": "https://api.github.com/users/jfarmer91/orgs",
        "repos_url": "https://api.github.com/users/jfarmer91/repos",
        "events_url": "https://api.github.com/users/jfarmer91/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jfarmer91/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:11Z",
      "updated_at": "2016-02-19T00:38:18Z",
      "closed_at": "2016-02-19T00:38:18Z",
      "pull_request": {
        "url": "https://api.github.com/repos/jfarmer91/test-bs-two/pulls/11",
        "html_url": "https://github.com/jfarmer91/test-bs-two/pull/11",
        "diff_url": "https://github.com/jfarmer91/test-bs-two/pull/11.diff",
        "patch_url": "https://github.com/jfarmer91/test-bs-two/pull/11.patch"
      },
      "body": null,
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/18",
      "repository_url": "https://api.github.com/repos/cs361-W16/Group2-2",
      "labels_url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/18/labels{/name}",
      "comments_url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/18/comments",
      "events_url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/18/events",
      "html_url": "https://github.com/cs361-W16/Group2-2/issues/18",
      "id": 134739713,
      "number": 18,
      "title": "Add Spanish card support",
      "user": {
        "login": "kirkpatt",
        "id": 16566398,
        "avatar_url": "https://avatars.githubusercontent.com/u/16566398?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kirkpatt",
        "html_url": "https://github.com/kirkpatt",
        "followers_url": "https://api.github.com/users/kirkpatt/followers",
        "following_url": "https://api.github.com/users/kirkpatt/following{/other_user}",
        "gists_url": "https://api.github.com/users/kirkpatt/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kirkpatt/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kirkpatt/subscriptions",
        "organizations_url": "https://api.github.com/users/kirkpatt/orgs",
        "repos_url": "https://api.github.com/users/kirkpatt/repos",
        "events_url": "https://api.github.com/users/kirkpatt/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kirkpatt/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:07Z",
      "updated_at": "2016-02-19T00:38:07Z",
      "closed_at": null,
      "body": "Add Spanish cards to the assets and change the model/view to allow the game to use them if selected.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/dotnet/buildtools/issues/463",
      "repository_url": "https://api.github.com/repos/dotnet/buildtools",
      "labels_url": "https://api.github.com/repos/dotnet/buildtools/issues/463/labels{/name}",
      "comments_url": "https://api.github.com/repos/dotnet/buildtools/issues/463/comments",
      "events_url": "https://api.github.com/repos/dotnet/buildtools/issues/463/events",
      "html_url": "https://github.com/dotnet/buildtools/pull/463",
      "id": 134739711,
      "number": 463,
      "title": "Workaround to copy native artifacts to the tools dir (for CLI upgrade)",
      "user": {
        "login": "dagood",
        "id": 12819531,
        "avatar_url": "https://avatars.githubusercontent.com/u/12819531?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dagood",
        "html_url": "https://github.com/dagood",
        "followers_url": "https://api.github.com/users/dagood/followers",
        "following_url": "https://api.github.com/users/dagood/following{/other_user}",
        "gists_url": "https://api.github.com/users/dagood/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dagood/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dagood/subscriptions",
        "organizations_url": "https://api.github.com/users/dagood/orgs",
        "repos_url": "https://api.github.com/users/dagood/repos",
        "events_url": "https://api.github.com/users/dagood/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dagood/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/dotnet/buildtools/labels/cla-already-signed",
          "name": "cla-already-signed",
          "color": "009800"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:07Z",
      "updated_at": "2016-02-19T00:38:08Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/dotnet/buildtools/pulls/463",
        "html_url": "https://github.com/dotnet/buildtools/pull/463",
        "diff_url": "https://github.com/dotnet/buildtools/pull/463.diff",
        "patch_url": "https://github.com/dotnet/buildtools/pull/463.patch"
      },
      "body": "In init-tools.sh we expect dotnet publish to copy the native artifacts in `tool-runtime/project.json` packages into the Tools dir. If we upgrade the version of dotnet CLI that we use, native artifact copy doesn't happen due to https://github.com/dotnet/cli/issues/710.\r\n\r\nThis works around it by manually copying the expected native artifacts to the Tools dir.\r\n\r\nOpen question: hardcoding the path feels really bad. Another option is to restore `tool-runtime/project.json` *again* into a folder under the tool runtime dir and copy the files out from there. This also would mean that we can use better wildcards rather than hardcoding the path, because we know only the packages we want are in the folder. This would slow down the init though. Is it worth it?\r\n\r\n(A reason to use `~/.nuget/packages` in the first place is that dotnet CLI doesn't support specifying a packages dir for publish. https://github.com/dotnet/cli/issues/1075)\r\n\r\n/cc @weshaggard ",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/nwops/puppet-repl/issues/4",
      "repository_url": "https://api.github.com/repos/nwops/puppet-repl",
      "labels_url": "https://api.github.com/repos/nwops/puppet-repl/issues/4/labels{/name}",
      "comments_url": "https://api.github.com/repos/nwops/puppet-repl/issues/4/comments",
      "events_url": "https://api.github.com/repos/nwops/puppet-repl/issues/4/events",
      "html_url": "https://github.com/nwops/puppet-repl/issues/4",
      "id": 134739708,
      "number": 4,
      "title": "list all functions currently in scope",
      "user": {
        "login": "logicminds",
        "id": 563900,
        "avatar_url": "https://avatars.githubusercontent.com/u/563900?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/logicminds",
        "html_url": "https://github.com/logicminds",
        "followers_url": "https://api.github.com/users/logicminds/followers",
        "following_url": "https://api.github.com/users/logicminds/following{/other_user}",
        "gists_url": "https://api.github.com/users/logicminds/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/logicminds/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/logicminds/subscriptions",
        "organizations_url": "https://api.github.com/users/logicminds/orgs",
        "repos_url": "https://api.github.com/users/logicminds/repos",
        "events_url": "https://api.github.com/users/logicminds/events{/privacy}",
        "received_events_url": "https://api.github.com/users/logicminds/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:05Z",
      "updated_at": "2016-02-19T00:38:05Z",
      "closed_at": null,
      "body": "",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/glennw/webrender/issues/189",
      "repository_url": "https://api.github.com/repos/glennw/webrender",
      "labels_url": "https://api.github.com/repos/glennw/webrender/issues/189/labels{/name}",
      "comments_url": "https://api.github.com/repos/glennw/webrender/issues/189/comments",
      "events_url": "https://api.github.com/repos/glennw/webrender/issues/189/events",
      "html_url": "https://github.com/glennw/webrender/issues/189",
      "id": 134739700,
      "number": 189,
      "title": "box-shadow + border-radius doesn't work",
      "user": {
        "login": "glennw",
        "id": 2350882,
        "avatar_url": "https://avatars.githubusercontent.com/u/2350882?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/glennw",
        "html_url": "https://github.com/glennw",
        "followers_url": "https://api.github.com/users/glennw/followers",
        "following_url": "https://api.github.com/users/glennw/following{/other_user}",
        "gists_url": "https://api.github.com/users/glennw/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/glennw/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/glennw/subscriptions",
        "organizations_url": "https://api.github.com/users/glennw/orgs",
        "repos_url": "https://api.github.com/users/glennw/repos",
        "events_url": "https://api.github.com/users/glennw/events{/privacy}",
        "received_events_url": "https://api.github.com/users/glennw/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:02Z",
      "updated_at": "2016-02-19T00:38:02Z",
      "closed_at": null,
      "body": "It currently sets a clip out rect around the visual box. Could we instead modify the box-shadow raster op shader to detect if inside the visual box and output 0?\r\n\r\ncc @pcwalton ",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/dimagi/commcarehq-prelogin/issues/62",
      "repository_url": "https://api.github.com/repos/dimagi/commcarehq-prelogin",
      "labels_url": "https://api.github.com/repos/dimagi/commcarehq-prelogin/issues/62/labels{/name}",
      "comments_url": "https://api.github.com/repos/dimagi/commcarehq-prelogin/issues/62/comments",
      "events_url": "https://api.github.com/repos/dimagi/commcarehq-prelogin/issues/62/events",
      "html_url": "https://github.com/dimagi/commcarehq-prelogin/pull/62",
      "id": 134739698,
      "number": 62,
      "title": "Fixes from bower move",
      "user": {
        "login": "biyeun",
        "id": 716573,
        "avatar_url": "https://avatars.githubusercontent.com/u/716573?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/biyeun",
        "html_url": "https://github.com/biyeun",
        "followers_url": "https://api.github.com/users/biyeun/followers",
        "following_url": "https://api.github.com/users/biyeun/following{/other_user}",
        "gists_url": "https://api.github.com/users/biyeun/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/biyeun/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/biyeun/subscriptions",
        "organizations_url": "https://api.github.com/users/biyeun/orgs",
        "repos_url": "https://api.github.com/users/biyeun/repos",
        "events_url": "https://api.github.com/users/biyeun/events{/privacy}",
        "received_events_url": "https://api.github.com/users/biyeun/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:01Z",
      "updated_at": "2016-02-19T00:38:12Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/dimagi/commcarehq-prelogin/pulls/62",
        "html_url": "https://github.com/dimagi/commcarehq-prelogin/pull/62",
        "diff_url": "https://github.com/dimagi/commcarehq-prelogin/pull/62.diff",
        "patch_url": "https://github.com/dimagi/commcarehq-prelogin/pull/62.patch"
      },
      "body": "@dannyroberts / anyone",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/powerbot/powerbot/issues/1309",
      "repository_url": "https://api.github.com/repos/powerbot/powerbot",
      "labels_url": "https://api.github.com/repos/powerbot/powerbot/issues/1309/labels{/name}",
      "comments_url": "https://api.github.com/repos/powerbot/powerbot/issues/1309/comments",
      "events_url": "https://api.github.com/repos/powerbot/powerbot/issues/1309/events",
      "html_url": "https://github.com/powerbot/powerbot/pull/1309",
      "id": 134739696,
      "number": 1309,
      "title": "Added small AntiBan",
      "user": {
        "login": "AutonomousCoding",
        "id": 16378140,
        "avatar_url": "https://avatars.githubusercontent.com/u/16378140?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AutonomousCoding",
        "html_url": "https://github.com/AutonomousCoding",
        "followers_url": "https://api.github.com/users/AutonomousCoding/followers",
        "following_url": "https://api.github.com/users/AutonomousCoding/following{/other_user}",
        "gists_url": "https://api.github.com/users/AutonomousCoding/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AutonomousCoding/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AutonomousCoding/subscriptions",
        "organizations_url": "https://api.github.com/users/AutonomousCoding/orgs",
        "repos_url": "https://api.github.com/users/AutonomousCoding/repos",
        "events_url": "https://api.github.com/users/AutonomousCoding/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AutonomousCoding/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:38:00Z",
      "updated_at": "2016-02-19T00:38:00Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/powerbot/powerbot/pulls/1309",
        "html_url": "https://github.com/powerbot/powerbot/pull/1309",
        "diff_url": "https://github.com/powerbot/powerbot/pull/1309.diff",
        "patch_url": "https://github.com/powerbot/powerbot/pull/1309.patch"
      },
      "body": "",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/esp8266/arduino-esp8266fs-plugin/issues/13",
      "repository_url": "https://api.github.com/repos/esp8266/arduino-esp8266fs-plugin",
      "labels_url": "https://api.github.com/repos/esp8266/arduino-esp8266fs-plugin/issues/13/labels{/name}",
      "comments_url": "https://api.github.com/repos/esp8266/arduino-esp8266fs-plugin/issues/13/comments",
      "events_url": "https://api.github.com/repos/esp8266/arduino-esp8266fs-plugin/issues/13/events",
      "html_url": "https://github.com/esp8266/arduino-esp8266fs-plugin/issues/13",
      "id": 134739686,
      "number": 13,
      "title": "SPIFFS hangs during uploading?",
      "user": {
        "login": "Rickgg",
        "id": 11305105,
        "avatar_url": "https://avatars.githubusercontent.com/u/11305105?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Rickgg",
        "html_url": "https://github.com/Rickgg",
        "followers_url": "https://api.github.com/users/Rickgg/followers",
        "following_url": "https://api.github.com/users/Rickgg/following{/other_user}",
        "gists_url": "https://api.github.com/users/Rickgg/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Rickgg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Rickgg/subscriptions",
        "organizations_url": "https://api.github.com/users/Rickgg/orgs",
        "repos_url": "https://api.github.com/users/Rickgg/repos",
        "events_url": "https://api.github.com/users/Rickgg/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Rickgg/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:56Z",
      "updated_at": "2016-02-19T00:37:56Z",
      "closed_at": null,
      "body": "When I try to flash the files, the SPIFFS uploader \"hangs\" and stops transmitting. I'm using Arduino IDE 1.6.5 and Mac OS X Yosemite. Any ideas as to why this could be happening?",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/omnidan/redux-recycle/issues/2",
      "repository_url": "https://api.github.com/repos/omnidan/redux-recycle",
      "labels_url": "https://api.github.com/repos/omnidan/redux-recycle/issues/2/labels{/name}",
      "comments_url": "https://api.github.com/repos/omnidan/redux-recycle/issues/2/comments",
      "events_url": "https://api.github.com/repos/omnidan/redux-recycle/issues/2/events",
      "html_url": "https://github.com/omnidan/redux-recycle/issues/2",
      "id": 134739684,
      "number": 2,
      "title": "Initial state must be always passed to reducer",
      "user": {
        "login": "steida",
        "id": 66249,
        "avatar_url": "https://avatars.githubusercontent.com/u/66249?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/steida",
        "html_url": "https://github.com/steida",
        "followers_url": "https://api.github.com/users/steida/followers",
        "following_url": "https://api.github.com/users/steida/following{/other_user}",
        "gists_url": "https://api.github.com/users/steida/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/steida/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/steida/subscriptions",
        "organizations_url": "https://api.github.com/users/steida/orgs",
        "repos_url": "https://api.github.com/users/steida/repos",
        "events_url": "https://api.github.com/users/steida/events{/privacy}",
        "received_events_url": "https://api.github.com/users/steida/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:55Z",
      "updated_at": "2016-02-19T00:37:55Z",
      "closed_at": null,
      "body": "My workaround.\r\n\r\n```js\r\nfunction recycle(reducer, actions = [], initialState) {\r\n    return (state, action) => {\r\n      if (actions.indexOf(action.type) >= 0) {\r\n        return reducer(initialState, {type: '@@redux-recycle/INIT'});\r\n        // if (initialState === undefined) {\r\n        //   return reducer(undefined, { type: '@@redux-recycle/INIT' })\r\n        // }\r\n        // return initialState\r\n      }\r\n      return reducer(state, action)\r\n    }\r\n  }\r\n```\r\n\r\nThat's because I am using immutable values, which have to be revived like this: https://github.com/este/este/blob/master/src/common/todos/reducer.js#L16\r\n",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/glumpy/glumpy/issues/71",
      "repository_url": "https://api.github.com/repos/glumpy/glumpy",
      "labels_url": "https://api.github.com/repos/glumpy/glumpy/issues/71/labels{/name}",
      "comments_url": "https://api.github.com/repos/glumpy/glumpy/issues/71/comments",
      "events_url": "https://api.github.com/repos/glumpy/glumpy/issues/71/events",
      "html_url": "https://github.com/glumpy/glumpy/issues/71",
      "id": 134739681,
      "number": 71,
      "title": "earth.py example broken",
      "user": {
        "login": "dopplershift",
        "id": 221526,
        "avatar_url": "https://avatars.githubusercontent.com/u/221526?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dopplershift",
        "html_url": "https://github.com/dopplershift",
        "followers_url": "https://api.github.com/users/dopplershift/followers",
        "following_url": "https://api.github.com/users/dopplershift/following{/other_user}",
        "gists_url": "https://api.github.com/users/dopplershift/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dopplershift/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dopplershift/subscriptions",
        "organizations_url": "https://api.github.com/users/dopplershift/orgs",
        "repos_url": "https://api.github.com/users/dopplershift/repos",
        "events_url": "https://api.github.com/users/dopplershift/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dopplershift/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:52Z",
      "updated_at": "2016-02-19T00:37:52Z",
      "closed_at": null,
      "body": "It looks like the `earth.py` example was broken by the move to `Arcball` from `Trackball`. This is the error I get (Python 3.5):\r\n```\r\nTraceback (most recent call last):\r\n  File \"earth.py\", line 63, in <module>\r\n    earth['transform'] = transform\r\n  File \"/Users/rmay/repos/glumpy/glumpy/gloo/program.py\", line 328, in __setitem__\r\n    snippet.attach(self)\r\n  File \"/Users/rmay/repos/glumpy/glumpy/transforms/transform.py\", line 73, in attach\r\n    self.dispatch_event(\"on_attach\", program)\r\n  File \"/Users/rmay/repos/glumpy/glumpy/app/window/event.py\", line 394, in dispatch_event\r\n    if getattr(self, event_type)(*args):\r\n  File \"/Users/rmay/repos/glumpy/glumpy/transforms/arcball.py\", line 178, in on_attach\r\n    self[\"view\"] = self._view\r\n  File \"/Users/rmay/repos/glumpy/glumpy/transforms/transform.py\", line 57, in __setitem__\r\n    Snippet.__setitem__(self, key, value)\r\n  File \"/Users/rmay/repos/glumpy/glumpy/gloo/snippet.py\", line 601, in __setitem__\r\n    raise IndexError(error)\r\nIndexError: Snippet does not have such key (\"arcball_view\")\r\n```\r\nIf I just change `Arcball` to `Trackball` it works.\r\n\r\nI noticed that the `Arcball` class is looking for `arcball.glsl`, which is not found anywhere in the repository. It looks like the code for `library.get()` will return the filename if a shader is not found--likely resulting in the code trying to use that filename as the shader source, causing the binding failure.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/Kademi/kademi-dev/issues/1345",
      "repository_url": "https://api.github.com/repos/Kademi/kademi-dev",
      "labels_url": "https://api.github.com/repos/Kademi/kademi-dev/issues/1345/labels{/name}",
      "comments_url": "https://api.github.com/repos/Kademi/kademi-dev/issues/1345/comments",
      "events_url": "https://api.github.com/repos/Kademi/kademi-dev/issues/1345/events",
      "html_url": "https://github.com/Kademi/kademi-dev/issues/1345",
      "id": 134739676,
      "number": 1345,
      "title": "ModuleStatus index records are not being updated",
      "user": {
        "login": "bradmac",
        "id": 826458,
        "avatar_url": "https://avatars.githubusercontent.com/u/826458?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bradmac",
        "html_url": "https://github.com/bradmac",
        "followers_url": "https://api.github.com/users/bradmac/followers",
        "following_url": "https://api.github.com/users/bradmac/following{/other_user}",
        "gists_url": "https://api.github.com/users/bradmac/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bradmac/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bradmac/subscriptions",
        "organizations_url": "https://api.github.com/users/bradmac/orgs",
        "repos_url": "https://api.github.com/users/bradmac/repos",
        "events_url": "https://api.github.com/users/bradmac/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bradmac/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/Kademi/kademi-dev/labels/enhancement",
          "name": "enhancement",
          "color": "84b6eb"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "bradmac",
        "id": 826458,
        "avatar_url": "https://avatars.githubusercontent.com/u/826458?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bradmac",
        "html_url": "https://github.com/bradmac",
        "followers_url": "https://api.github.com/users/bradmac/followers",
        "following_url": "https://api.github.com/users/bradmac/following{/other_user}",
        "gists_url": "https://api.github.com/users/bradmac/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bradmac/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bradmac/subscriptions",
        "organizations_url": "https://api.github.com/users/bradmac/orgs",
        "repos_url": "https://api.github.com/users/bradmac/repos",
        "events_url": "https://api.github.com/users/bradmac/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bradmac/received_events",
        "type": "User",
        "site_admin": false
      },
      "milestone": {
        "url": "https://api.github.com/repos/Kademi/kademi-dev/milestones/178",
        "html_url": "https://github.com/Kademi/kademi-dev/milestones/Galatasaray",
        "labels_url": "https://api.github.com/repos/Kademi/kademi-dev/milestones/178/labels",
        "id": 1582455,
        "number": 178,
        "title": "Galatasaray",
        "description": "In this deployment we need to reindex all ecommerce sites because of fixing this issue https://github.com/Kademi/kademi-dev/issues/1184 which needs to make some changes to index mapping",
        "creator": {
          "login": "bradmac",
          "id": 826458,
          "avatar_url": "https://avatars.githubusercontent.com/u/826458?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/bradmac",
          "html_url": "https://github.com/bradmac",
          "followers_url": "https://api.github.com/users/bradmac/followers",
          "following_url": "https://api.github.com/users/bradmac/following{/other_user}",
          "gists_url": "https://api.github.com/users/bradmac/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/bradmac/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/bradmac/subscriptions",
          "organizations_url": "https://api.github.com/users/bradmac/orgs",
          "repos_url": "https://api.github.com/users/bradmac/repos",
          "events_url": "https://api.github.com/users/bradmac/events{/privacy}",
          "received_events_url": "https://api.github.com/users/bradmac/received_events",
          "type": "User",
          "site_admin": false
        },
        "open_issues": 45,
        "closed_issues": 10,
        "state": "open",
        "created_at": "2016-02-15T03:59:57Z",
        "updated_at": "2016-02-19T00:37:51Z",
        "due_on": "2016-02-21T17:00:00Z",
        "closed_at": null
      },
      "comments": 0,
      "created_at": "2016-02-19T00:37:50Z",
      "updated_at": "2016-02-19T00:37:50Z",
      "closed_at": null,
      "body": "",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/cloudcello/PerformanceAnalytics/issues/2",
      "repository_url": "https://api.github.com/repos/cloudcello/PerformanceAnalytics",
      "labels_url": "https://api.github.com/repos/cloudcello/PerformanceAnalytics/issues/2/labels{/name}",
      "comments_url": "https://api.github.com/repos/cloudcello/PerformanceAnalytics/issues/2/comments",
      "events_url": "https://api.github.com/repos/cloudcello/PerformanceAnalytics/issues/2/events",
      "html_url": "https://github.com/cloudcello/PerformanceAnalytics/issues/2",
      "id": 134739675,
      "number": 2,
      "title": "Documentation for ES()",
      "user": {
        "login": "cloudcello",
        "id": 4019314,
        "avatar_url": "https://avatars.githubusercontent.com/u/4019314?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cloudcello",
        "html_url": "https://github.com/cloudcello",
        "followers_url": "https://api.github.com/users/cloudcello/followers",
        "following_url": "https://api.github.com/users/cloudcello/following{/other_user}",
        "gists_url": "https://api.github.com/users/cloudcello/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cloudcello/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cloudcello/subscriptions",
        "organizations_url": "https://api.github.com/users/cloudcello/orgs",
        "repos_url": "https://api.github.com/users/cloudcello/repos",
        "events_url": "https://api.github.com/users/cloudcello/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cloudcello/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:50Z",
      "updated_at": "2016-02-19T00:37:50Z",
      "closed_at": null,
      "body": "portfolio_method arg includes 'marginal' but the code does not handle 'marginal' only 'single' and 'component'",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/dmlc/xgboost/issues/845",
      "repository_url": "https://api.github.com/repos/dmlc/xgboost",
      "labels_url": "https://api.github.com/repos/dmlc/xgboost/issues/845/labels{/name}",
      "comments_url": "https://api.github.com/repos/dmlc/xgboost/issues/845/comments",
      "events_url": "https://api.github.com/repos/dmlc/xgboost/issues/845/events",
      "html_url": "https://github.com/dmlc/xgboost/pull/845",
      "id": 134739663,
      "number": 845,
      "title": "[Documents] update windows instructions",
      "user": {
        "login": "thirdwing",
        "id": 1547093,
        "avatar_url": "https://avatars.githubusercontent.com/u/1547093?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/thirdwing",
        "html_url": "https://github.com/thirdwing",
        "followers_url": "https://api.github.com/users/thirdwing/followers",
        "following_url": "https://api.github.com/users/thirdwing/following{/other_user}",
        "gists_url": "https://api.github.com/users/thirdwing/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/thirdwing/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thirdwing/subscriptions",
        "organizations_url": "https://api.github.com/users/thirdwing/orgs",
        "repos_url": "https://api.github.com/users/thirdwing/repos",
        "events_url": "https://api.github.com/users/thirdwing/events{/privacy}",
        "received_events_url": "https://api.github.com/users/thirdwing/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:46Z",
      "updated_at": "2016-02-19T00:37:46Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/dmlc/xgboost/pulls/845",
        "html_url": "https://github.com/dmlc/xgboost/pull/845",
        "diff_url": "https://github.com/dmlc/xgboost/pull/845.diff",
        "patch_url": "https://github.com/dmlc/xgboost/pull/845.patch"
      },
      "body": "",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/CodeForAfrica/aleph/issues/1",
      "repository_url": "https://api.github.com/repos/CodeForAfrica/aleph",
      "labels_url": "https://api.github.com/repos/CodeForAfrica/aleph/issues/1/labels{/name}",
      "comments_url": "https://api.github.com/repos/CodeForAfrica/aleph/issues/1/comments",
      "events_url": "https://api.github.com/repos/CodeForAfrica/aleph/issues/1/events",
      "html_url": "https://github.com/CodeForAfrica/aleph/pull/1",
      "id": 134739662,
      "number": 1,
      "title": "Google oauth sign-in",
      "user": {
        "login": "andkamau",
        "id": 647123,
        "avatar_url": "https://avatars.githubusercontent.com/u/647123?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/andkamau",
        "html_url": "https://github.com/andkamau",
        "followers_url": "https://api.github.com/users/andkamau/followers",
        "following_url": "https://api.github.com/users/andkamau/following{/other_user}",
        "gists_url": "https://api.github.com/users/andkamau/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/andkamau/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/andkamau/subscriptions",
        "organizations_url": "https://api.github.com/users/andkamau/orgs",
        "repos_url": "https://api.github.com/users/andkamau/repos",
        "events_url": "https://api.github.com/users/andkamau/events{/privacy}",
        "received_events_url": "https://api.github.com/users/andkamau/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:45Z",
      "updated_at": "2016-02-19T00:37:45Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/CodeForAfrica/aleph/pulls/1",
        "html_url": "https://github.com/CodeForAfrica/aleph/pull/1",
        "diff_url": "https://github.com/CodeForAfrica/aleph/pull/1.diff",
        "patch_url": "https://github.com/CodeForAfrica/aleph/pull/1.patch"
      },
      "body": "Replaced sign-in on web interface from [investigativedashboard.org](https://investigativedashboard.org/) to [google](google.com)",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/nwops/puppet-repl/issues/3",
      "repository_url": "https://api.github.com/repos/nwops/puppet-repl",
      "labels_url": "https://api.github.com/repos/nwops/puppet-repl/issues/3/labels{/name}",
      "comments_url": "https://api.github.com/repos/nwops/puppet-repl/issues/3/comments",
      "events_url": "https://api.github.com/repos/nwops/puppet-repl/issues/3/events",
      "html_url": "https://github.com/nwops/puppet-repl/issues/3",
      "id": 134739653,
      "number": 3,
      "title": "allow import of a file ",
      "user": {
        "login": "logicminds",
        "id": 563900,
        "avatar_url": "https://avatars.githubusercontent.com/u/563900?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/logicminds",
        "html_url": "https://github.com/logicminds",
        "followers_url": "https://api.github.com/users/logicminds/followers",
        "following_url": "https://api.github.com/users/logicminds/following{/other_user}",
        "gists_url": "https://api.github.com/users/logicminds/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/logicminds/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/logicminds/subscriptions",
        "organizations_url": "https://api.github.com/users/logicminds/orgs",
        "repos_url": "https://api.github.com/users/logicminds/repos",
        "events_url": "https://api.github.com/users/logicminds/events{/privacy}",
        "received_events_url": "https://api.github.com/users/logicminds/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:39Z",
      "updated_at": "2016-02-19T00:37:39Z",
      "closed_at": null,
      "body": "We should allow a file to be imported and then evaulated.  This will help with trying new things out instead of copy/paste.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/issues/702",
      "repository_url": "https://api.github.com/repos/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000",
      "labels_url": "https://api.github.com/repos/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/issues/702/labels{/name}",
      "comments_url": "https://api.github.com/repos/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/issues/702/comments",
      "events_url": "https://api.github.com/repos/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/issues/702/events",
      "html_url": "https://github.com/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/pull/702",
      "id": 134739651,
      "number": 702,
      "title": "Done",
      "user": {
        "login": "MemoryB",
        "id": 7037775,
        "avatar_url": "https://avatars.githubusercontent.com/u/7037775?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MemoryB",
        "html_url": "https://github.com/MemoryB",
        "followers_url": "https://api.github.com/users/MemoryB/followers",
        "following_url": "https://api.github.com/users/MemoryB/following{/other_user}",
        "gists_url": "https://api.github.com/users/MemoryB/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MemoryB/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MemoryB/subscriptions",
        "organizations_url": "https://api.github.com/users/MemoryB/orgs",
        "repos_url": "https://api.github.com/users/MemoryB/repos",
        "events_url": "https://api.github.com/users/MemoryB/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MemoryB/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:39Z",
      "updated_at": "2016-02-19T00:37:39Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/pulls/702",
        "html_url": "https://github.com/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/pull/702",
        "diff_url": "https://github.com/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/pull/702.diff",
        "patch_url": "https://github.com/learn-co-students/first-lab-ruby-learn-cli-nitrous-q-000/pull/702.patch"
      },
      "body": null,
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/reactioncommerce/reaction/issues/796",
      "repository_url": "https://api.github.com/repos/reactioncommerce/reaction",
      "labels_url": "https://api.github.com/repos/reactioncommerce/reaction/issues/796/labels{/name}",
      "comments_url": "https://api.github.com/repos/reactioncommerce/reaction/issues/796/comments",
      "events_url": "https://api.github.com/repos/reactioncommerce/reaction/issues/796/events",
      "html_url": "https://github.com/reactioncommerce/reaction/issues/796",
      "id": 134739647,
      "number": 796,
      "title": "update reaction-factories, tests for v0.12",
      "user": {
        "login": "aaronjudd",
        "id": 439959,
        "avatar_url": "https://avatars.githubusercontent.com/u/439959?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/aaronjudd",
        "html_url": "https://github.com/aaronjudd",
        "followers_url": "https://api.github.com/users/aaronjudd/followers",
        "following_url": "https://api.github.com/users/aaronjudd/following{/other_user}",
        "gists_url": "https://api.github.com/users/aaronjudd/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/aaronjudd/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/aaronjudd/subscriptions",
        "organizations_url": "https://api.github.com/users/aaronjudd/orgs",
        "repos_url": "https://api.github.com/users/aaronjudd/repos",
        "events_url": "https://api.github.com/users/aaronjudd/events{/privacy}",
        "received_events_url": "https://api.github.com/users/aaronjudd/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/reactioncommerce/reaction/labels/in%20progress",
          "name": "in progress",
          "color": "009800"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "aaronjudd",
        "id": 439959,
        "avatar_url": "https://avatars.githubusercontent.com/u/439959?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/aaronjudd",
        "html_url": "https://github.com/aaronjudd",
        "followers_url": "https://api.github.com/users/aaronjudd/followers",
        "following_url": "https://api.github.com/users/aaronjudd/following{/other_user}",
        "gists_url": "https://api.github.com/users/aaronjudd/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/aaronjudd/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/aaronjudd/subscriptions",
        "organizations_url": "https://api.github.com/users/aaronjudd/orgs",
        "repos_url": "https://api.github.com/users/aaronjudd/repos",
        "events_url": "https://api.github.com/users/aaronjudd/events{/privacy}",
        "received_events_url": "https://api.github.com/users/aaronjudd/received_events",
        "type": "User",
        "site_admin": false
      },
      "milestone": {
        "url": "https://api.github.com/repos/reactioncommerce/reaction/milestones/29",
        "html_url": "https://github.com/reactioncommerce/reaction/milestones/v0.12.0",
        "labels_url": "https://api.github.com/repos/reactioncommerce/reaction/milestones/29/labels",
        "id": 1470494,
        "number": 29,
        "title": "v0.12.0",
        "description": "Layouts, hierarchical Tag navigation, Theme editor.",
        "creator": {
          "login": "aaronjudd",
          "id": 439959,
          "avatar_url": "https://avatars.githubusercontent.com/u/439959?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aaronjudd",
          "html_url": "https://github.com/aaronjudd",
          "followers_url": "https://api.github.com/users/aaronjudd/followers",
          "following_url": "https://api.github.com/users/aaronjudd/following{/other_user}",
          "gists_url": "https://api.github.com/users/aaronjudd/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aaronjudd/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aaronjudd/subscriptions",
          "organizations_url": "https://api.github.com/users/aaronjudd/orgs",
          "repos_url": "https://api.github.com/users/aaronjudd/repos",
          "events_url": "https://api.github.com/users/aaronjudd/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aaronjudd/received_events",
          "type": "User",
          "site_admin": false
        },
        "open_issues": 16,
        "closed_issues": 6,
        "state": "open",
        "created_at": "2015-12-22T00:55:40Z",
        "updated_at": "2016-02-19T00:37:35Z",
        "due_on": "2016-02-24T08:00:00Z",
        "closed_at": null
      },
      "comments": 0,
      "created_at": "2016-02-19T00:37:35Z",
      "updated_at": "2016-02-19T00:37:35Z",
      "closed_at": null,
      "body": "update reaction-factories, export faker to client, wrap custom faker with ReactionFaker so that it can be handled separately but export as faker.reaction for compatibility.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/Mark-Lauman/DominionPicker/issues/49",
      "repository_url": "https://api.github.com/repos/Mark-Lauman/DominionPicker",
      "labels_url": "https://api.github.com/repos/Mark-Lauman/DominionPicker/issues/49/labels{/name}",
      "comments_url": "https://api.github.com/repos/Mark-Lauman/DominionPicker/issues/49/comments",
      "events_url": "https://api.github.com/repos/Mark-Lauman/DominionPicker/issues/49/events",
      "html_url": "https://github.com/Mark-Lauman/DominionPicker/issues/49",
      "id": 134739644,
      "number": 49,
      "title": "If Attack, Require Reaction Card",
      "user": {
        "login": "ddewar10",
        "id": 15822357,
        "avatar_url": "https://avatars.githubusercontent.com/u/15822357?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ddewar10",
        "html_url": "https://github.com/ddewar10",
        "followers_url": "https://api.github.com/users/ddewar10/followers",
        "following_url": "https://api.github.com/users/ddewar10/following{/other_user}",
        "gists_url": "https://api.github.com/users/ddewar10/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ddewar10/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ddewar10/subscriptions",
        "organizations_url": "https://api.github.com/users/ddewar10/orgs",
        "repos_url": "https://api.github.com/users/ddewar10/repos",
        "events_url": "https://api.github.com/users/ddewar10/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ddewar10/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:34Z",
      "updated_at": "2016-02-19T00:37:34Z",
      "closed_at": null,
      "body": "It would be great to have the option in the rules to force a reaction card in the set if an attack card is picked.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/measurement-kit/measurement-kit/issues/382",
      "repository_url": "https://api.github.com/repos/measurement-kit/measurement-kit",
      "labels_url": "https://api.github.com/repos/measurement-kit/measurement-kit/issues/382/labels{/name}",
      "comments_url": "https://api.github.com/repos/measurement-kit/measurement-kit/issues/382/comments",
      "events_url": "https://api.github.com/repos/measurement-kit/measurement-kit/issues/382/events",
      "html_url": "https://github.com/measurement-kit/measurement-kit/pull/382",
      "id": 134739639,
      "number": 382,
      "title": "Feature/improve net implementation",
      "user": {
        "login": "bassosimone",
        "id": 337298,
        "avatar_url": "https://avatars.githubusercontent.com/u/337298?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bassosimone",
        "html_url": "https://github.com/bassosimone",
        "followers_url": "https://api.github.com/users/bassosimone/followers",
        "following_url": "https://api.github.com/users/bassosimone/following{/other_user}",
        "gists_url": "https://api.github.com/users/bassosimone/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bassosimone/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bassosimone/subscriptions",
        "organizations_url": "https://api.github.com/users/bassosimone/orgs",
        "repos_url": "https://api.github.com/users/bassosimone/repos",
        "events_url": "https://api.github.com/users/bassosimone/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bassosimone/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/measurement-kit/measurement-kit/labels/enhancement",
          "name": "enhancement",
          "color": "84b6eb"
        },
        {
          "url": "https://api.github.com/repos/measurement-kit/measurement-kit/labels/on%20hold",
          "name": "on hold",
          "color": "006b75"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": {
        "url": "https://api.github.com/repos/measurement-kit/measurement-kit/milestones/10",
        "html_url": "https://github.com/measurement-kit/measurement-kit/milestones/release-0.2.0-alpha.1",
        "labels_url": "https://api.github.com/repos/measurement-kit/measurement-kit/milestones/10/labels",
        "id": 1578584,
        "number": 10,
        "title": "release-0.2.0-alpha.1",
        "description": "",
        "creator": {
          "login": "bassosimone",
          "id": 337298,
          "avatar_url": "https://avatars.githubusercontent.com/u/337298?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/bassosimone",
          "html_url": "https://github.com/bassosimone",
          "followers_url": "https://api.github.com/users/bassosimone/followers",
          "following_url": "https://api.github.com/users/bassosimone/following{/other_user}",
          "gists_url": "https://api.github.com/users/bassosimone/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/bassosimone/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/bassosimone/subscriptions",
          "organizations_url": "https://api.github.com/users/bassosimone/orgs",
          "repos_url": "https://api.github.com/users/bassosimone/repos",
          "events_url": "https://api.github.com/users/bassosimone/events{/privacy}",
          "received_events_url": "https://api.github.com/users/bassosimone/received_events",
          "type": "User",
          "site_admin": false
        },
        "open_issues": 5,
        "closed_issues": 0,
        "state": "open",
        "created_at": "2016-02-11T21:46:57Z",
        "updated_at": "2016-02-19T00:37:29Z",
        "due_on": "2016-03-12T23:00:00Z",
        "closed_at": null
      },
      "comments": 0,
      "created_at": "2016-02-19T00:37:29Z",
      "updated_at": "2016-02-19T00:37:29Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/measurement-kit/measurement-kit/pulls/382",
        "html_url": "https://github.com/measurement-kit/measurement-kit/pull/382",
        "diff_url": "https://github.com/measurement-kit/measurement-kit/pull/382.diff",
        "patch_url": "https://github.com/measurement-kit/measurement-kit/pull/382.patch"
      },
      "body": "",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/brews-brothers/BrewsBrothersChillerFrontEnd/issues/32",
      "repository_url": "https://api.github.com/repos/brews-brothers/BrewsBrothersChillerFrontEnd",
      "labels_url": "https://api.github.com/repos/brews-brothers/BrewsBrothersChillerFrontEnd/issues/32/labels{/name}",
      "comments_url": "https://api.github.com/repos/brews-brothers/BrewsBrothersChillerFrontEnd/issues/32/comments",
      "events_url": "https://api.github.com/repos/brews-brothers/BrewsBrothersChillerFrontEnd/issues/32/events",
      "html_url": "https://github.com/brews-brothers/BrewsBrothersChillerFrontEnd/pull/32",
      "id": 134739614,
      "number": 32,
      "title": "Changed src to cdn link from node modules AGAIN",
      "user": {
        "login": "lfontana",
        "id": 11932370,
        "avatar_url": "https://avatars.githubusercontent.com/u/11932370?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lfontana",
        "html_url": "https://github.com/lfontana",
        "followers_url": "https://api.github.com/users/lfontana/followers",
        "following_url": "https://api.github.com/users/lfontana/following{/other_user}",
        "gists_url": "https://api.github.com/users/lfontana/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lfontana/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lfontana/subscriptions",
        "organizations_url": "https://api.github.com/users/lfontana/orgs",
        "repos_url": "https://api.github.com/users/lfontana/repos",
        "events_url": "https://api.github.com/users/lfontana/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lfontana/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:15Z",
      "updated_at": "2016-02-19T00:37:15Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/brews-brothers/BrewsBrothersChillerFrontEnd/pulls/32",
        "html_url": "https://github.com/brews-brothers/BrewsBrothersChillerFrontEnd/pull/32",
        "diff_url": "https://github.com/brews-brothers/BrewsBrothersChillerFrontEnd/pull/32.diff",
        "patch_url": "https://github.com/brews-brothers/BrewsBrothersChillerFrontEnd/pull/32.patch"
      },
      "body": "",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/17",
      "repository_url": "https://api.github.com/repos/cs361-W16/Group2-2",
      "labels_url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/17/labels{/name}",
      "comments_url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/17/comments",
      "events_url": "https://api.github.com/repos/cs361-W16/Group2-2/issues/17/events",
      "html_url": "https://github.com/cs361-W16/Group2-2/issues/17",
      "id": 134739609,
      "number": 17,
      "title": "Prompt for Spanish/English cards",
      "user": {
        "login": "kirkpatt",
        "id": 16566398,
        "avatar_url": "https://avatars.githubusercontent.com/u/16566398?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kirkpatt",
        "html_url": "https://github.com/kirkpatt",
        "followers_url": "https://api.github.com/users/kirkpatt/followers",
        "following_url": "https://api.github.com/users/kirkpatt/following{/other_user}",
        "gists_url": "https://api.github.com/users/kirkpatt/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kirkpatt/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kirkpatt/subscriptions",
        "organizations_url": "https://api.github.com/users/kirkpatt/orgs",
        "repos_url": "https://api.github.com/users/kirkpatt/repos",
        "events_url": "https://api.github.com/users/kirkpatt/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kirkpatt/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:13Z",
      "updated_at": "2016-02-19T00:37:13Z",
      "closed_at": null,
      "body": "Add a prompt to select between Spanish and English cards. On page load, persistent option, etc.",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/elaheh-sadredini/Handwritten-Digit-Recognition/issues/3",
      "repository_url": "https://api.github.com/repos/elaheh-sadredini/Handwritten-Digit-Recognition",
      "labels_url": "https://api.github.com/repos/elaheh-sadredini/Handwritten-Digit-Recognition/issues/3/labels{/name}",
      "comments_url": "https://api.github.com/repos/elaheh-sadredini/Handwritten-Digit-Recognition/issues/3/comments",
      "events_url": "https://api.github.com/repos/elaheh-sadredini/Handwritten-Digit-Recognition/issues/3/events",
      "html_url": "https://github.com/elaheh-sadredini/Handwritten-Digit-Recognition/pull/3",
      "id": 134739608,
      "number": 3,
      "title": "First pull",
      "user": {
        "login": "elaheh-sadredini",
        "id": 17326070,
        "avatar_url": "https://avatars.githubusercontent.com/u/17326070?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/elaheh-sadredini",
        "html_url": "https://github.com/elaheh-sadredini",
        "followers_url": "https://api.github.com/users/elaheh-sadredini/followers",
        "following_url": "https://api.github.com/users/elaheh-sadredini/following{/other_user}",
        "gists_url": "https://api.github.com/users/elaheh-sadredini/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/elaheh-sadredini/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/elaheh-sadredini/subscriptions",
        "organizations_url": "https://api.github.com/users/elaheh-sadredini/orgs",
        "repos_url": "https://api.github.com/users/elaheh-sadredini/repos",
        "events_url": "https://api.github.com/users/elaheh-sadredini/events{/privacy}",
        "received_events_url": "https://api.github.com/users/elaheh-sadredini/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:13Z",
      "updated_at": "2016-02-19T00:37:13Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/elaheh-sadredini/Handwritten-Digit-Recognition/pulls/3",
        "html_url": "https://github.com/elaheh-sadredini/Handwritten-Digit-Recognition/pull/3",
        "diff_url": "https://github.com/elaheh-sadredini/Handwritten-Digit-Recognition/pull/3.diff",
        "patch_url": "https://github.com/elaheh-sadredini/Handwritten-Digit-Recognition/pull/3.patch"
      },
      "body": "First pull request by Elaheh",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/jpatokal/openflights/issues/474",
      "repository_url": "https://api.github.com/repos/jpatokal/openflights",
      "labels_url": "https://api.github.com/repos/jpatokal/openflights/issues/474/labels{/name}",
      "comments_url": "https://api.github.com/repos/jpatokal/openflights/issues/474/comments",
      "events_url": "https://api.github.com/repos/jpatokal/openflights/issues/474/events",
      "html_url": "https://github.com/jpatokal/openflights/issues/474",
      "id": 134739607,
      "number": 474,
      "title": "Update airport INTERNATIONAL DALLAS (DFW/KLGA)",
      "user": {
        "login": "jpatokal",
        "id": 278761,
        "avatar_url": "https://avatars.githubusercontent.com/u/278761?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jpatokal",
        "html_url": "https://github.com/jpatokal",
        "followers_url": "https://api.github.com/users/jpatokal/followers",
        "following_url": "https://api.github.com/users/jpatokal/following{/other_user}",
        "gists_url": "https://api.github.com/users/jpatokal/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jpatokal/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jpatokal/subscriptions",
        "organizations_url": "https://api.github.com/users/jpatokal/orgs",
        "repos_url": "https://api.github.com/users/jpatokal/repos",
        "events_url": "https://api.github.com/users/jpatokal/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jpatokal/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/jpatokal/openflights/labels/airport",
          "name": "airport",
          "color": "ededed"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:13Z",
      "updated_at": "2016-02-19T00:37:13Z",
      "closed_at": null,
      "body": "New airport edit suggestion submitted by memordida:\n\nUPDATE airports SET name='INTERNATIONAL DALLAS', city='DALLAS', country='United States', iata='DFW', icao='KLGA', x=-73.872608, y=40.777245, elevation=22, timezone=-5, dst='A' WHERE apid=3697;\n\nExisting, potentially conflicting airport information:\n\n```\nArray\n(\n    [name] => Dallas Fort Worth Intl\n    [city] => Dallas-Fort Worth\n    [country] => United States\n    [iata] => DFW\n    [icao] => KDFW\n    [x] => -97.037997\n    [y] => 32.896828\n    [elevation] => 607\n    [apid] => 3670\n    [uid] => \n    [timezone] => -6\n    [dst] => A\n    [tz_id] => America/Chicago\n)\n\nArray\n(\n    [name] => La Guardia\n    [city] => New York\n    [country] => United States\n    [iata] => LGA\n    [icao] => KLGA\n    [x] => -73.872608\n    [y] => 40.777245\n    [elevation] => 22\n    [apid] => 3697\n    [uid] => \n    [timezone] => -5\n    [dst] => A\n    [tz_id] => America/New_York\n)\n\n```\n\nCross-check this edit on other sites with compatible licensing:\n- OurAirports: http://ourairports.com/airports/KLGA/pilot-info.html\n- Wikipedia: http://www.google.com/search?q=wikipedia%20KLGA%20airport&btnI",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/SakuragiYoshimasa/FractalTest/issues/6",
      "repository_url": "https://api.github.com/repos/SakuragiYoshimasa/FractalTest",
      "labels_url": "https://api.github.com/repos/SakuragiYoshimasa/FractalTest/issues/6/labels{/name}",
      "comments_url": "https://api.github.com/repos/SakuragiYoshimasa/FractalTest/issues/6/comments",
      "events_url": "https://api.github.com/repos/SakuragiYoshimasa/FractalTest/issues/6/events",
      "html_url": "https://github.com/SakuragiYoshimasa/FractalTest/issues/6",
      "id": 134739601,
      "number": 6,
      "title": "テスト",
      "user": {
        "login": "SakuragiYoshimasa",
        "id": 10016741,
        "avatar_url": "https://avatars.githubusercontent.com/u/10016741?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/SakuragiYoshimasa",
        "html_url": "https://github.com/SakuragiYoshimasa",
        "followers_url": "https://api.github.com/users/SakuragiYoshimasa/followers",
        "following_url": "https://api.github.com/users/SakuragiYoshimasa/following{/other_user}",
        "gists_url": "https://api.github.com/users/SakuragiYoshimasa/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/SakuragiYoshimasa/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/SakuragiYoshimasa/subscriptions",
        "organizations_url": "https://api.github.com/users/SakuragiYoshimasa/orgs",
        "repos_url": "https://api.github.com/users/SakuragiYoshimasa/repos",
        "events_url": "https://api.github.com/users/SakuragiYoshimasa/events{/privacy}",
        "received_events_url": "https://api.github.com/users/SakuragiYoshimasa/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:09Z",
      "updated_at": "2016-02-19T00:37:09Z",
      "closed_at": null,
      "body": "\n![alt text](http://snapissue/47861339-1804289383.jpg)\n",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/gocql/gocql/issues/659",
      "repository_url": "https://api.github.com/repos/gocql/gocql",
      "labels_url": "https://api.github.com/repos/gocql/gocql/issues/659/labels{/name}",
      "comments_url": "https://api.github.com/repos/gocql/gocql/issues/659/comments",
      "events_url": "https://api.github.com/repos/gocql/gocql/issues/659/events",
      "html_url": "https://github.com/gocql/gocql/pull/659",
      "id": 134739600,
      "number": 659,
      "title": "Don't crash on bad peers.",
      "user": {
        "login": "muirrn",
        "id": 11356572,
        "avatar_url": "https://avatars.githubusercontent.com/u/11356572?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/muirrn",
        "html_url": "https://github.com/muirrn",
        "followers_url": "https://api.github.com/users/muirrn/followers",
        "following_url": "https://api.github.com/users/muirrn/following{/other_user}",
        "gists_url": "https://api.github.com/users/muirrn/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/muirrn/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/muirrn/subscriptions",
        "organizations_url": "https://api.github.com/users/muirrn/orgs",
        "repos_url": "https://api.github.com/users/muirrn/repos",
        "events_url": "https://api.github.com/users/muirrn/events{/privacy}",
        "received_events_url": "https://api.github.com/users/muirrn/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:09Z",
      "updated_at": "2016-02-19T00:37:09Z",
      "closed_at": null,
      "pull_request": {
        "url": "https://api.github.com/repos/gocql/gocql/pulls/659",
        "html_url": "https://github.com/gocql/gocql/pull/659",
        "diff_url": "https://github.com/gocql/gocql/pull/659.diff",
        "patch_url": "https://github.com/gocql/gocql/pull/659.patch"
      },
      "body": "It's possible (or at least was possible), to be left with invalid\r\nsystem.peers entries in your db after changing your\r\nring (https://issues.apache.org/jira/browse/CASSANDRA-6053 is at least\r\none way it used to be able to happen). If this happens (or someone who\r\nis already in this state upgrades gocql and is trying to doing peer\r\ndiscovery), ideally gocql would continue working on the good peers\r\ninstead of crashing trying to parse the bad peers. I made two changes\r\nwith this goal in mind:\r\n\r\n1. Fix version string parsing to not crash if version is too short.\r\n2. Skip peers if we fail parsing the version string (but still return\r\n   the peers we were able to parse).\r\n3. When waiting for schema agreement, skip peers that have an empty\r\n   schema_version (otherwise it times out and fails).\r\n\r\nOur ring had peer entries with null \"rack\", \"release_version\",\r\n\"schema_version\", and \"tokens\".",
      "score": 1.0
    },
    {
      "url": "https://api.github.com/repos/bojcheski/datejs/issues/192",
      "repository_url": "https://api.github.com/repos/bojcheski/datejs",
      "labels_url": "https://api.github.com/repos/bojcheski/datejs/issues/192/labels{/name}",
      "comments_url": "https://api.github.com/repos/bojcheski/datejs/issues/192/comments",
      "events_url": "https://api.github.com/repos/bojcheski/datejs/issues/192/events",
      "html_url": "https://github.com/bojcheski/datejs/issues/192",
      "id": 134739591,
      "number": 192,
      "title": ".addMonths('6') != .addMonths(6). String problem",
      "user": {
        "login": "GoogleCodeExporter",
        "id": 9614759,
        "avatar_url": "https://avatars.githubusercontent.com/u/9614759?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/GoogleCodeExporter",
        "html_url": "https://github.com/GoogleCodeExporter",
        "followers_url": "https://api.github.com/users/GoogleCodeExporter/followers",
        "following_url": "https://api.github.com/users/GoogleCodeExporter/following{/other_user}",
        "gists_url": "https://api.github.com/users/GoogleCodeExporter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/GoogleCodeExporter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/GoogleCodeExporter/subscriptions",
        "organizations_url": "https://api.github.com/users/GoogleCodeExporter/orgs",
        "repos_url": "https://api.github.com/users/GoogleCodeExporter/repos",
        "events_url": "https://api.github.com/users/GoogleCodeExporter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/GoogleCodeExporter/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "url": "https://api.github.com/repos/bojcheski/datejs/labels/auto-migrated",
          "name": "auto-migrated",
          "color": "ededed"
        },
        {
          "url": "https://api.github.com/repos/bojcheski/datejs/labels/Priority-Medium",
          "name": "Priority-Medium",
          "color": "ededed"
        },
        {
          "url": "https://api.github.com/repos/bojcheski/datejs/labels/Type-Defect",
          "name": "Type-Defect",
          "color": "ededed"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "milestone": null,
      "comments": 0,
      "created_at": "2016-02-19T00:37:06Z",
      "updated_at": "2016-02-19T00:37:06Z",
      "closed_at": null,
      "body": "```\nDate.now().addMonths(6)\nTue Mar 24 2015\n\nDate.now().addMonths('6')\nWed Mar 24 2021\n\n\n```\n\nOriginal issue reported on code.google.com by `Dmitri.B...@gmail.com` on 24 Sep 2014 at 4:14",
      "score": 1.0
    }
  ]
};